name: bloc_test_async
description: "A bloc extension to test async operations using bloc_test."
version: 0.1.2
repository: https://github.com/tusche/bloc_test_async

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.2.1
  bloc_concurrency: ^0.3.0
  get_it: ^9.3.0
  equatable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
