name: bloc_test_async
description: "A bloc extension to test async operations using bloc_test."
version: 0.1.0
repository: https://github.com/tusche/bloc_test_async

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  get_it: ^7.7.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
